[build-system]
requires = ["setuptools >= 46.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neural-mixture"
version = "0.1.0"
requires-python = ">=3.10"
description = "Post-processing tools for OpenFOAM RANS simulations vs LES reference data."
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "pyvista",
    "scikit-learn",
    "torch",
    "json"
]

[tool.setuptools.packages.find]
include = ["neural_mixture*"]

[project.scripts]
postprocess_compressor = "neural_mixture.postprocess_compressor:main"
setup_simulation = "neural_mixture.setup_simulation:main"
generate_dataset = "neural_mixture.generate_dataset:main"
