PolyRT = 
symm( T1()*	( ThetaR_[0] + ThetaR_[1]*Iv1() + ThetaR_[2]*Iv2()
	+ ThetaR_[3]*pow(Iv1(),2) + ThetaR_[4]*Iv1()*Iv2() + ThetaR_[5]*pow(Iv2(),2)
	+ ThetaR_[6]*pow(Iv1(),3) + ThetaR_[7]*pow(Iv1(),2)*Iv2() + ThetaR_[8]*Iv1()*pow(Iv2(),2) + ThetaR_[9]*pow(Iv2(),3)
	+ ThetaR_[10]*pow(Iv1(),4) + ThetaR_[11]*pow(Iv1(),3)*Iv2() + ThetaR_[12]*pow(Iv1(),2)*pow(Iv2(),2) + ThetaR_[13]*Iv1()*pow(Iv2(),3) + ThetaR_[14]*pow(Iv2(),4)
	+ ThetaR_[15]*pow(Iv1(),5) + ThetaR_[16]*pow(Iv1(),4)*Iv2() + ThetaR_[17]*pow(Iv1(),3)*pow(Iv2(),2) + ThetaR_[18]*pow(Iv1(),2)*pow(Iv2(),3) + ThetaR_[19]*Iv1()*pow(Iv2(),4) + ThetaR_[20]*pow(Iv2(),5)
	+ ThetaR_[21]*pow(Iv1(),6) + ThetaR_[22]*pow(Iv1(),5)*Iv2() + ThetaR_[23]*pow(Iv1(),4)*pow(Iv2(),2) + ThetaR_[24]*pow(Iv1(),3)*pow(Iv2(),3) + ThetaR_[25]*pow(Iv1(),2)*pow(Iv2(),4) + ThetaR_[26]*Iv1()*pow(Iv2(),5) + ThetaR_[27]*pow(Iv2(),6))

+T2()*( ThetaR_[28] + ThetaR_[29]*Iv1() + ThetaR_[30]*Iv2()
	+ ThetaR_[31]*pow(Iv1(),2) + ThetaR_[32]*Iv1()*Iv2() + ThetaR_[33]*pow(Iv2(),2)
	+ ThetaR_[34]*pow(Iv1(),3) + ThetaR_[35]*pow(Iv1(),2)*Iv2() + ThetaR_[36]*Iv1()*pow(Iv2(),2) + ThetaR_[37]*pow(Iv2(),3)
	+ ThetaR_[38]*pow(Iv1(),4) + ThetaR_[39]*pow(Iv1(),3)*Iv2() + ThetaR_[40]*pow(Iv1(),2)*pow(Iv2(),2) + ThetaR_[41]*Iv1()*pow(Iv2(),3) + ThetaR_[42]*pow(Iv2(),4)
	+ ThetaR_[43]*pow(Iv1(),5) + ThetaR_[44]*pow(Iv1(),4)*Iv2() + ThetaR_[45]*pow(Iv1(),3)*pow(Iv2(),2) + ThetaR_[46]*pow(Iv1(),2)*pow(Iv2(),3) + ThetaR_[47]*Iv1()*pow(Iv2(),4) + ThetaR_[48]*pow(Iv2(),5)
	+ ThetaR_[49]*pow(Iv1(),6) + ThetaR_[50]*pow(Iv1(),5)*Iv2() + ThetaR_[51]*pow(Iv1(),4)*pow(Iv2(),2) + ThetaR_[52]*pow(Iv1(),3)*pow(Iv2(),3) + ThetaR_[53]*pow(Iv1(),2)*pow(Iv2(),4) + ThetaR_[54]*Iv1()*pow(Iv2(),5) + ThetaR_[55]*pow(Iv2(),6))


+T3()*( ThetaR_[56] + ThetaR_[57]*Iv1() + ThetaR_[58]*Iv2()
	+ ThetaR_[59]*pow(Iv1(),2) + ThetaR_[60]*Iv1()*Iv2() + ThetaR_[61]*pow(Iv2(),2)
	+ ThetaR_[62]*pow(Iv1(),3) + ThetaR_[63]*pow(Iv1(),2)*Iv2() + ThetaR_[64]*Iv1()*pow(Iv2(),2) + ThetaR_[65]*pow(Iv2(),3)
	+ ThetaR_[66]*pow(Iv1(),4) + ThetaR_[67]*pow(Iv1(),3)*Iv2() + ThetaR_[68]*pow(Iv1(),2)*pow(Iv2(),2) + ThetaR_[69]*Iv1()*pow(Iv2(),3) + ThetaR_[70]*pow(Iv2(),4)
	+ ThetaR_[71]*pow(Iv1(),5) + ThetaR_[72]*pow(Iv1(),4)*Iv2() + ThetaR_[73]*pow(Iv1(),3)*pow(Iv2(),2) + ThetaR_[74]*pow(Iv1(),2)*pow(Iv2(),3) + ThetaR_[75]*Iv1()*pow(Iv2(),4) + ThetaR_[76]*pow(Iv2(),5)
	+ ThetaR_[77]*pow(Iv1(),6) + ThetaR_[78]*pow(Iv1(),5)*Iv2() + ThetaR_[79]*pow(Iv1(),4)*pow(Iv2(),2) + ThetaR_[80]*pow(Iv1(),3)*pow(Iv2(),3) + ThetaR_[81]*pow(Iv1(),2)*pow(Iv2(),4) + ThetaR_[82]*Iv1()*pow(Iv2(),5) + ThetaR_[83]*pow(Iv2(),6)));
	
